# Generated by Django 4.0.4 on 2022-06-12 12:53

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=75, verbose_name='Стаття')),
                ('title_uk', models.CharField(db_index=True, max_length=75, null=True, verbose_name='Стаття')),
                ('title_en', models.CharField(db_index=True, max_length=75, null=True, verbose_name='Стаття')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('img', models.ImageField(upload_to='articles_photo', verbose_name='Картинка')),
                ('content', tinymce.models.HTMLField(db_index=True, verbose_name='Контент')),
                ('content_uk', tinymce.models.HTMLField(db_index=True, null=True, verbose_name='Контент')),
                ('content_en', tinymce.models.HTMLField(db_index=True, null=True, verbose_name='Контент')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ('-time_create',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=20, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=17, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=50, verbose_name='Адреса електронної пошти')),
                ('city', models.CharField(max_length=20, verbose_name='Місто')),
                ('address', models.CharField(max_length=70, verbose_name='Адреса')),
                ('details', models.TextField(verbose_name='Деталі запиту')),
                ('status', models.BooleanField(default=False, verbose_name='Статус замовлення')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
            ],
            options={
                'verbose_name': 'Замовлення на оренду',
                'verbose_name_plural': 'Замовлення на оренду',
                'ordering': ('-time_create',),
            },
        ),
        migrations.CreateModel(
            name='LogoOrd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=20, verbose_name='Прізвище')),
                ('phone', models.CharField(max_length=17, verbose_name='Номер телефону')),
                ('email', models.EmailField(max_length=50, verbose_name='Адреса електронної пошти')),
                ('details', models.TextField(verbose_name='Деталі запиту')),
                ('status', models.BooleanField(default=False, verbose_name='Статус замовлення')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
            ],
            options={
                'verbose_name': 'Замовлення на лого килим',
                'verbose_name_plural': 'Замовлення на лого килими',
                'ordering': ('-time_create',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=75, verbose_name='Назва')),
                ('title_uk', models.CharField(db_index=True, max_length=75, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(db_index=True, max_length=75, null=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', tinymce.models.HTMLField(db_index=True, verbose_name='Опис')),
                ('description_uk', tinymce.models.HTMLField(db_index=True, null=True, verbose_name='Опис')),
                ('description_en', tinymce.models.HTMLField(db_index=True, null=True, verbose_name='Опис')),
                ('img_1', models.ImageField(upload_to='photo', verbose_name='Картинка')),
                ('img_2', models.ImageField(upload_to='photo', verbose_name='Доп картинка')),
                ('img_3', models.ImageField(upload_to='photo', verbose_name='Доп картинка')),
                ('prise_1', models.IntegerField(verbose_name='1 раз на місяць')),
                ('prise_2', models.IntegerField(verbose_name='2 рази на місяць')),
                ('prise_3', models.IntegerField(verbose_name='1 раз в тиждень')),
                ('prise_4', models.IntegerField(verbose_name='2 рази на тиждень')),
                ('prise_5', models.IntegerField(verbose_name='3 рази на тиждень')),
                ('prise_6', models.IntegerField(verbose_name='4 рази на тиждень')),
                ('prise_7', models.IntegerField(verbose_name='5 разів на тиждень')),
                ('prise_8', models.IntegerField(verbose_name='6 разів на тиждень')),
                ('prise_9', models.IntegerField(verbose_name='кожен день(в Сб) - додатковий килим')),
                ('status', models.BooleanField(default=True, verbose_name='Доступність')),
            ],
            options={
                'verbose_name': 'Оренда килимових покриттів',
                'verbose_name_plural': 'Оренда килимових покриттів',
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=75, verbose_name='Назва')),
                ('title_uk', models.CharField(db_index=True, max_length=75, null=True, verbose_name='Назва')),
                ('title_en', models.CharField(db_index=True, max_length=75, null=True, verbose_name='Назва')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', tinymce.models.HTMLField(db_index=True, verbose_name='Опис')),
                ('description_uk', tinymce.models.HTMLField(db_index=True, null=True, verbose_name='Опис')),
                ('description_en', tinymce.models.HTMLField(db_index=True, null=True, verbose_name='Опис')),
                ('img_1', models.ImageField(upload_to='photo', verbose_name='Картинка')),
                ('img_2', models.ImageField(upload_to='photo', verbose_name='Доп картинка')),
                ('img_3', models.ImageField(upload_to='photo', verbose_name='Доп картинка')),
                ('color', models.CharField(max_length=20, verbose_name='Колір')),
                ('color_hex', models.CharField(max_length=20, verbose_name='Код кольору')),
                ('prise', models.IntegerField(verbose_name='Ціна')),
                ('count', models.IntegerField(verbose_name='Кількість')),
                ('status', models.BooleanField(default=True, verbose_name='Доступність')),
            ],
            options={
                'verbose_name': 'Спеціальна пропозиція',
                'verbose_name_plural': 'Спецпропозиції',
            },
        ),
    ]
