# Generated by Django 4.0.4 on 2022-05-22 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_available',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='specialoffer',
            old_name='is_available',
            new_name='status',
        ),
    ]
