# Generated by Django 4.0.4 on 2022-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='img',
            field=models.ImageField(upload_to='photo', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='img_1',
            field=models.ImageField(upload_to='photo', verbose_name='Доп картинка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='img_2',
            field=models.ImageField(upload_to='photo', verbose_name='Доп картинка'),
        ),
    ]
