# Generated by Django 4.0.4 on 2022-05-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_order_img_alter_order_img_1_alter_order_img_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='specialoffer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(db_index=True, max_length=75, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specialoffer',
            name='title',
            field=models.CharField(db_index=True, max_length=75, verbose_name='Название'),
        ),
    ]
