# Generated by Django 4.0.4 on 2022-05-31 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_alter_specialoffer_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FillUrl',
        ),
    ]
