# Generated by Django 4.0.4 on 2022-05-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_specialoffer_color_hex_alter_order_prise_9'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialoffer',
            name='color_hex',
            field=models.CharField(max_length=20, verbose_name='Код цвета'),
        ),
    ]
